### ISSUE TITLE
it's showing an import error 

### ISSUE THREAD

**Issue by spartan-1997** [scrapeInfo/hacakthons-scrape#3]
![screenshot from 2017-07-11 00-52-49](https://user-images.githubusercontent.com/24358501/28035856-bf18fc54-65d3-11e7-8794-15e7440d8429.png)

**Comment by schedutron** [comment]
Which Python version are you using? On Python2, change the line to `from urllib import urlopen`. However, the script is in Python3, so using Python3 is recommended.

**Comment by schedutron** [comment]
Install Python3, then type `pip3 -r requirements.txt` and then type `python3 -i scrapeHack.py` in your terminal. Then follow the README instructions.

**Comment by spartan-1997** [comment]
yeah i am using python 2 .
Doing the changes
